### PR TITLE
Drop 'python_versions' from release-conf and build py3 wheel only.

### PR DESCRIPTION
**Pull request by jpopelka**

### CODE REVIEW

**Comment by rpitonak** [comment]
So release-bot is now unable to release any python2 project on PyPi, right? What does this mean for maintainers? Do they need to change release-bot.conf, after this will get merged?

**Comment by jpopelka** [comment]
> maintainers? Do they need to change release-bot.conf

no, the 'python_versions' in their release-conf will be ignored

**Comment by TomasTomecek** [comment]
design wise, I'm personally okay with this; on the other hand, we should make sure that it's possible to upload sdist and py3 wheel - that way people would still be able to satisfy python 2, I'm typing on phone, let me check code.

**Comment by rpitonak** [comment]
[test]

**Comment by rpitonak** [comment]
[test]

**Pull request merged**
