### PR TITLE
Add v1 logo design of release bot

### PR DESCRIPTION
**Pull request by surfer19**
Hi,
it could be nice if release bot has some nice logo right? I tried some concepts and robot with package in his hands could be descriptive enough, what do you think? 
It's combination of flat and material design.
Please checkout my design logo v1 extended logo and design guide - it would be great if you will give me some feedback.
I look forward to your response!

### CODE REVIEW

**Comment by surfer19** [comment]
I'm happy that you like it!
I forgot to mention, which of extended logo v1/v2 you like more?
Let me know so we can add it to README :)

**Comment by surfer19** [comment]
v1..
logo-bot-extended-v1
v2..
logo-bot-extended-v2

**Comment by jpopelka** [comment]
I like v1.

btw, I've changed the avatar of https://github.com/usercont-release-bot

**Comment by surfer19** [comment]
I had to do some changes, so logo now hopefully fit well in README.
If you have any suggestions please let me know.
Also I added `.sketch` file so anyone can edit logo in the future.

Screenshot 2019-07-31 at 15 27 40

**Pull request merged**
