### PR TITLE
Updated tests.

### PR DESCRIPTION
**Pull request by Aniket-Pradhan**
Forgot to update the tests in the previous PR (#192 ), which were causing the tests to fail.

### CODE REVIEW

**Comment by jpopelka** [comment]
I still see some failures when running tests locally, but I might have something wrongly configured here, so let's merge and we'll see. We can have another round (PR) in the worst case.

**Comment by jpopelka** [comment]
[Build #446](https://travis-ci.org/user-cont/release-bot/builds/509413502)

**Comment by Aniket-Pradhan** [comment]
I didn't get any failures when I ran the tests locally (using the token, as well). 😕

**Comment by jpopelka** [comment]
Yeah, we need to finally move the CI to Centos CI so we could run all the tests even in pull requests (for now some are skipped in PRs and the complete set is run only after a merge to master). But for now this is all we have.

**Comment by Aniket-Pradhan** [comment]
Well, I found out what was causing the tests to fail. Should I create another PR?

I don't know why my local tests were passing, earlier.

**Comment by jpopelka** [comment]
> Should I create another PR?

sure, don't ask :-)

**Pull request merged**
