### PR TITLE
Stripped author_name and author_email fields in init.

### PR DESCRIPTION
**Pull request by Aniket-Pradhan**
A minor PR.

Solves #225

### CODE REVIEW

**Comment by Aniket-Pradhan** [comment]
I had not seen that earlier. 

Also, what do you think of handling exceptions during the init phase? Like, for any wrong value, the program should not terminate, but ask the user to re-enter a correct value?

**Comment by TomasTomecek** [comment]
> Also, what do you think of handling exceptions during the init phase?

They can and will happen.

> Like, for any wrong value, the program should not terminate, but ask the user to re-enter a correct value?

Yup, re-enter makes sense.

**Comment by Aniket-Pradhan** [comment]
The only place where the bot can actually ask for re-entering some value is when it encounters an exception when [typecasting](https://github.com/user-cont/release-bot/blob/master/release_bot/init_repo.py#L107) to `int`. 

Other fields are string/bool objects and I don't think we can actually evaluate if the info entered by the user is correct or not.

We can also add some tests so that [`git config ...`](https://github.com/user-cont/release-bot/blob/master/release_bot/init_repo.py#L95) commands do not return ambiguous or empty output. For example, what if someone has not set the global email ID, or set some random string in it?

**Comment by TomasTomecek** [comment]
> Other fields are string/bool objects and I don't think we can actually evaluate if the info entered by the user is correct or not.

Oki, sounds good

> We can also add some tests so that [`git config ...`](https://github.com/user-cont/release-bot/blob/master/release_bot/init_repo.py#L95) commands do not return ambiguous or empty output. For example, what if someone has not set the global email ID, or set some random string in it?

ideally, just expect failures and then provide useful info to users

> Should I proceed with such tests?

Yes, please!

**Pull request merged**
